import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import wrapper, { AppDispatch, useAppSelector } from '@/store';
import { useDispatch } from 'react-redux';
import { counterActions } from '@/store/modules/counter';
import { GetServerSideProps } from 'next';

export default function Home() {
  const count = useAppSelector(({ counter }) => counter.count);
  const dispatch = useDispatch<AppDispatch>();

  const handleClickUp = () => {
    dispatch(counterActions.increment());
  };

  const handleClickDown = () => {
    dispatch(counterActions.decrement());
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{count}</h1>
      <div className={styles.buttons}>
        <button onClick={handleClickUp}>up</button>
        <button onClick={handleClickDown}>down</button>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps(
    (store) =>
      async ({ req, res, query, ...rest }) => {
        return { props: {} };
      }
  );

// Home.getInitialProps = wrapper.getInitialPageProps(
//   (store) =>
//     ({ pathname, req, res }) => {}
// );
